// packages/lit/src/index.ts
/** Lit reactive controller. @license Apache-2.0 */
import type { ReactiveController, ReactiveControllerHost } from 'lit';
import type { QaraaSession } from '@atqan/qaraa-client';
import type {
  QuranLocation,
  ReadingSnapshot,
  RecitationObservation,
} from '@atqan/qaraa-core';
import {
  createAdapterController,
  type QaraaStatus,
} from '@atqan/qaraa-client';

export class QaraaSessionController implements ReactiveController {
  private readonly controller;
  snapshot: ReadingSnapshot;
  status: QaraaStatus = 'idle';
  error: Error | null = null;
  private release: (() => void) | undefined;
  private readonly host: ReactiveControllerHost;

  constructor(
    host: ReactiveControllerHost,
    session: QaraaSession,
  ) {
    this.host = host;
    this.controller = createAdapterController(session);
    this.snapshot = this.controller.read().snapshot;
    host.addController(this);
  }

  hostConnected(): void {
    if (this.release) return;
    this.controller.connect();
    const update = (): void => {
      const next = this.controller.read();
      this.snapshot = next.snapshot;
      this.status = next.status;
      this.error = next.error;
      this.host.requestUpdate();
    };
    update();
    this.release = this.controller.subscribe(update);
  }

  hostDisconnected(): void {
    this.release?.();
    this.release = undefined;
    void this.controller.dispose();
  }

  submit(observation: RecitationObservation): Promise<ReadingSnapshot> {
    return this.controller.submit(observation);
  }

  reset(location?: QuranLocation): Promise<ReadingSnapshot> {
    return this.controller.reset(location);
  }

  close(): Promise<void> {
    return this.controller.close();
  }
}

// packages/react/src/index.ts
/** React session hook. @license Apache-2.0 */
import { useEffect, useMemo, useSyncExternalStore } from 'react';
import type { ReadingSnapshot, RecitationObservation, QuranLocation } from '@atqan/qaraa-core';
import type { QaraaSession } from '@atqan/qaraa-client';
import { createAdapterController, type QaraaState, type QaraaStatus } from '@atqan/qaraa-client';
export type UseQaraaSessionResult = Readonly<{ snapshot: ReadingSnapshot; status: QaraaStatus; error: Error | null; submit(observation: RecitationObservation): Promise<ReadingSnapshot>; reset(location?: QuranLocation): Promise<ReadingSnapshot>; close(): Promise<void> }>;
/** Unmount releases the subscription only; close is explicit caller intent. */
export function useQaraaSession(session: QaraaSession): UseQaraaSessionResult {
 const controller = useMemo(() => createAdapterController(session), [session]);
 useEffect(() => { controller.connect(); return () => { void controller.dispose(); }; }, [controller]);
 const state = useSyncExternalStore(controller.subscribe, controller.read, controller.read) as QaraaState;
 return useMemo(() => ({ ...state, submit: controller.submit, reset: controller.reset, close: controller.close }), [state, controller]);
}
